import type { Metadata } from "next";
import { Geist, Geist_Mono, Tiro_Devanagari_Marathi, Yellowtail } from "next/font/google";
import "./globals.css";

const devanagari = Tiro_Devanagari_Marathi({
  variable: "--font-devanagari",
  subsets: ["latin"],
  weight: ["400"],
})

const yellowtail = Yellowtail({
  variable: "--font-yellowtail",
  subsets: ["latin"],
  weight: ["400"],
});

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${devanagari.variable} ${yellowtail.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
